# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

permissions:
  contents: read

jobs:
  build-linux:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyoxidizer
    - name: Build
      run: |
        pyoxidizer build --path .  --release
    - name: Archive artifacts
      uses: actions/upload-artifact@v3
      with:
        name: linux-build
        path: |
            build
            !build/**/*.txt

  build-linux-old:

    runs-on: ubuntu-latest
    container: debian:11
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.7
      uses: actions/setup-python@v3
      with:
        python-version: "3.7"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyoxidizer
    - name: Build
      run: |
        pyoxidizer build --path .  --release
    - name: Archive artifacts
      uses: actions/upload-artifact@v3
      with:
        name: linux-build-debian-11
        path: |
            build
            !build/**/*.txt
  build-macos:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyoxidizer
    - name: Build
      run: |
        pyoxidizer build --path .  --release
    - name: Archive artifacts
      uses: actions/upload-artifact@v3
      with:
        name: mac-build
        path: |
            build
            !build/**/*.txt

  build-windows:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyoxidizer
    - name: Build
      run: |
        pyoxidizer build --path .  --release
    - name: Archive artifacts
      uses: actions/upload-artifact@v3
      with:
        name: windows-build
        path: |
            build
            !build/**/*.txt